-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2sF+vF//0nJDYZx/
A1oQQu2vGgS2kGDQdtI0wvtz4UagCgYIKoZIzj0DAQehRANCAAS2M1XuwGYNYlrk
vxQeJPBhFIre1L9PgNpLLcpfF4HUMvWiNYtcY4WS+0BWUDeU7hfc7Ot0ofkq/e++
zR5vHYEy
-----END PRIVATE KEY-----